version: '3.8'

services:
  db:
      image: postgres:15
      restart: always
      environment:
        POSTGRES_DB: accounts_database
        POSTGRES_USER: nima
        POSTGRES_PASSWORD: 3858nima
      volumes:   
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U nima -d accounts_database"]
        interval: 5s
        timeout: 5s
        retries: 10


  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: accounts-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 15

  app:
    build: .
    container_name: accounts-app
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      db:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  celery_worker:
    build: .
    container_name: accounts-celery-worker
    volumes:
      - .:/code
    command: celery -A core worker -l info
    depends_on:
      db:
        condition: service_healthy
      rabbit:
        condition: service_healthy

  celery_beat:
    build: .
    container_name: accounts-celery-beat
    volumes:
      - .:/code
    command: celery -A core beat -l info
    depends_on:
      db:
        condition: service_healthy
      rabbit:
        condition: service_healthy

volumes:
  postgres_data:
  rabbitmq_data:
