# Generated by Django 5.2.7 on 2025-11-26 01:41

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='device',
            name='longitude',
        ),
    ]
