# Generated by Django 5.2.7 on 2025-11-14 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_device_location_remove_device_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='devices.device'),
        ),
    ]
