# Generated by Django 5.2.7 on 2025-11-26 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_device_latitude_remove_device_longitude'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='address',
            field=models.ForeignKey(
                to='accounts.address',
                on_delete=django.db.models.deletion.CASCADE,
                null=True,
                blank=True,
            ),
        ),
    ]
