# Generated by Django 5.2.7 on 2025-11-26 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_address'),
        ('devices', '0003_auto_20251126_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
            preserve_default=False,
        ),
    ]
