# Generated by Django 5.2.7 on 2025-11-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_devicelog_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='auth_token',
            field=models.CharField(default='default', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelog',
            name='device_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
