# Generated by Django 5.2.7 on 2025-11-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_device_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='devicelog',
            name='device_time',
        ),
        migrations.RemoveField(
            model_name='devicelog',
            name='payload',
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(default='null'),
            preserve_default=False,
        ),
    ]
