# Generated by Django 5.2.7 on 2025-11-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_email'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('title', 'address'), name='unique_title_address'),
        ),
    ]
