# Generated by Django 5.2.7 on 2025-11-05 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_unique_title_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fingerprint',
            old_name='template',
            new_name='template_data',
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='finger_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fingerprint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to=settings.AUTH_USER_MODEL),
        ),
    ]
