# Generated by Django 5.2.7 on 2025-11-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_template_fingerprint_template_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='finger_name',
            field=models.CharField(blank=True, choices=[('right_thumb', 'Right Thumb'), ('right_pointer', 'Right Pointer'), ('right_middle', 'Right Milddle'), ('right_ring', 'Right Ring'), ('right_pinky', 'Right Pinky'), ('left_thumb', 'Left Thumb'), ('left_pointer', 'Left Pointer'), ('left_middle', 'Left Middle'), ('left_ring', 'Left Ring'), ('left_pinky', 'Left Pinky')], max_length=50, null=True),
        ),
    ]
