"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
import sys
import logging
import json
import socket
from celery.schedules import crontab
from cmreslogging.handlers import CMRESHandler

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# ========================
# Quick-start development settings
# ========================
SECRET_KEY = 'django-insecure-)pb)i6gy1_^a-2xhf-fy4vy$%ng=bjf%fzt=-fux@0hxaxjs_!'
DEBUG = True
ALLOWED_HOSTS = []

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SESSION_COOKIE_AGE = 1209600 

SESSION_COOKIE_SECURE = not DEBUG

SESSION_COOKIE_HTTPONLY = True

# ========================
# Applications
# ========================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'widget_tweaks',

    # Local apps
    'accounts',
    'attendance',
    'devices',
]

AUTH_USER_MODEL = 'accounts.CustomUser'

# ========================
# Middleware
# ========================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Custom
    'accounts.middleware.ElasticsearchLogMiddleware',
]

# ========================
# REST Framework
# ========================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ]
}

# ========================
# URLs & Templates
# ========================
ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# ========================
# Database
# ========================
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'accounts_database',
        'USER': 'nima',
        'PASSWORD': '3858nima',
        'HOST': 'db',
        'PORT': 5432,
    }
}
# Password validation
# ========================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ========================
# Internationalization
# ========================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ========================
# Static files
# ========================
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========================
# Celery
# ========================
CELERY_BROKER_URL = "amqp://admin:admin123@rabbit:5672//"
# CELERY_RESULT_BACKEND = "redis://redis:6379/2"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

CELERY_BEAT_SCHEDULE = {
    'check-every-hour': {
        'task': 'devices.tasks.check_devices_status',
        'schedule': crontab(minute=0, hour='*'),
    },
}

# ========================
# Elasticsearch
# ========================
ELASTICSEARCH_HOST = 'http://elasticsearch:9200'
ELASTICSEARCH_INDEX = 'django_request_logs'

# ========================
# Redis Caching & Sessions
# ========================
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://redis:6379/1",
#     }
# }
# SESSION_ENGINE = "django.contrib.sessions.backends.cache"

# ========================
# Logging
# ========================
LOGSTASH_HOST = os.getenv("LOGSTASH_HOST", "localhost")
LOGSTASH_PORT = int(os.getenv("LOGSTASH_PORT", "5959"))


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

class JsonFormatter(logging.Formatter):
    """Custom JSON formatter for logs"""
    def format(self, record):
        log_record = {
            "message": record.getMessage(),
            "level": record.levelname,
            "logger": record.name,
            "time": self.formatTime(record, self.datefmt),
            "hostname": socket.gethostname(),
        }
        return json.dumps(log_record)

# Logging handlers
LOGGING_HANDLERS = {
    "console": {
        "class": "logging.StreamHandler",
        "formatter": "verbose",
    }
}

# Elasticsearch handler (فقط وقتی Celery نیست)
if "celery" not in sys.argv:
    LOGGING_HANDLERS["elasticsearch"] = {
        "class": "cmreslogging.handlers.CMRESHandler",
        "hosts": [{"host": "elasticsearch", "port": 9200}],
        "es_index_name": "django_logs",
        "auth_type": CMRESHandler.AuthType.NO_AUTH,
    }

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": LOGGING_HANDLERS,
    "formatters": {
        "json": {"()": JsonFormatter},
        "verbose": {"format": "[{levelname}] {asctime} {name}: {message}", "style": "{"},
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}


# برای تست - ایمیل در کنسول چاپ میشه
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# وقتی SMTP رو تنظیم کردی، این رو جایگزین کن:
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'nima.mojarradi83@gmail.com'
EMAIL_HOST_PASSWORD = 'hirf zlle iahz eood'
DEFAULT_FROM_EMAIL = 'nima.mojarradi83@gmail.com'
