# Generated by Django 5.2.7 on 2025-11-14 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendanceevent_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceevent',
            name='date',
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
